### ISSUE TITLE
/assign only considers the last assignment if multiple assignments are done in one comment.

### ISSUE THREAD

**Issue by anvithks** [Huawei-PaaS/ci-bot#18]
**What is the Issue?**  
If I try to assign multiple people to a PR by using the following:
```
/assign xyz  

/assign abc
```

Only `abc` gets assigned to the PR.

** How can the issue be reproduced?**  
1. Create a new PR.  
2. In a new comment try to assign multiple users by entering a /assign command on new lines.  
3. The bot only picks up the second assignment.  

** What is the expected output?**  
Every /assign should be considered and processed in the order of assignment.

**Comment by m1093782566** [comment]
cc @pavan187

**Comment by pavan187** [comment]
@anvithks 

/assign @xxxx @yyyy @zzzz  ('@' must be specified)
should be able to assign multiple reviews, this is already supported, request to again assign once and let me know.


cc @m1093782566

**Comment by pavan187** [comment]
> **What is the Issue?**
> If I try to assign multiple people to a PR by using the following:
> 
> ```
> /assign xyz  
> 
> /assign abc
> ```
> Only `abc` gets assigned to the PR.
> 
> ** How can the issue be reproduced?**
> 
> 1. Create a new PR.
> 2. In a new comment try to assign multiple users by entering a /assign command on new lines.
> 3. The bot only picks up the second assignment.
> 
> ** What is the expected output?**
> Every /assign should be considered and processed in the order of assignment.

@anvithks , At the moment, we are supporting multiple assignee by doing following format

/assing @xxx, @yyy, @zzz format. 

the below format support is not there at the moment
/assign @xyz
/assign @abc

May be we can take this as a enhancement for /assign in the future.

For now you can add multiple assignee by following format.
/assign @xyz @abc

**Comment by m1093782566** [comment]
We should add the support.

BTW, k8s-ci-robot support this feature as well.
