### ISSUE TITLE
Dockerize the CI Bot 

### ISSUE THREAD

**Issue by asifdxtreme** [Huawei-PaaS/ci-bot#20]
Make a docker image of CI bot so that it can be run in the containerized env like k8s...

**Comment by m1093782566** [comment]
@sids-b Can you please assign this task to the right person?

**Comment by sids-b** [comment]
> @sids-b Can you please assign this task to the right person?

Sure @m1093782566 . I will assign it to someone today :)

**Comment by sids-b** [comment]
@srivatsav123 , please help with this task, Thanks :)

**Comment by srivatsav123** [comment]
ok

**Comment by sids-b** [comment]
Closing this Issue with PR #23
